version: '3.8'

services:
  mi-microservicio:
    build: . 
    ports:
      - "3000:3000" 
    restart: always 
    deploy:
      resources:
        limits:
          cpus: '0.5'     
          memory: 512M    